FROM ruby:3.0-alpine
LABEL maintainer "RubyOn <rubyon@me.com>"

RUN apk update && apk upgrade

RUN apk add build-base nodejs yarn mariadb-dev

RUN gem install bundler

WORKDIR /app

COPY Gemfile /app

RUN bundle install

COPY . /app

RUN rm -rf config/database.rb && cp app/db/development_database.rb app/config/database.rb

RUN yarn dev

EXPOSE 8080

CMD ["sh","start_dev.sh"]
